"""Default section payloads for the marketing CMS.

When a `PageContent` row exists but has zero sections (newly seeded by
`seed_default_pages` on a fresh DB, or after the page-content table was
just created), we fill it with sensible starter sections matching the
current static React copy. This means:
  - On first sign-in, the boss opens "Marketing pages → Home" and sees
    real content they can edit, not a blank canvas.
  - After publishing, the public site renders from the DB and looks
    identical to the existing static fallback.
  - Existing rows with sections are never overwritten — boss edits win.

Pages stay UNPUBLISHED on first seed so the boss confirms each one before
it goes live. The static React fallback continues to serve until then.

Adding default content for a new page:
  1. Add an entry to `DEFAULTS` keyed by slug.
  2. The dict is a list of section dicts matching the schema in
     app/schemas/page_sections.py — IDs are auto-generated by Pydantic
     when the seed runs.
"""
from __future__ import annotations

from sqlalchemy.orm import Session

from app.models import PageContent
from app.schemas.page_sections import validate_sections


# ---------------------------------------------------------------------------
# Section payloads
# ---------------------------------------------------------------------------

HOME_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "QUATA Digital",
        "title": "The connected operating system for Africa's next decade.",
        "subtitle": "Payments, business operations and commerce — built on one rail. Made in Bamenda, designed for the continent.",
        "primary_cta_label": "Become a partner",
        "primary_cta_href": "/partners",
        "secondary_cta_label": "Talk to the team",
        "secondary_cta_href": "/contact",
    },
    {
        "type": "feature_grid",
        "eyebrow": "Why QUATA",
        "title": "Built differently — on purpose.",
        "subtitle": "Most platforms ship one product and stop. QUATA is engineered as one rail so every additional product makes the rest cheaper, faster and more useful.",
        "columns": 3,
        "items": [
            {"title": "One rail, many products", "body": "Payments, business operations and commerce surfaces share the same identity, wallet and infrastructure."},
            {"title": "Network compounding", "body": "Each new product on the rail strengthens the rest. The 7th product is cheaper to build than the 1st."},
            {"title": "Trust by default", "body": "Compliance, fraud monitoring and audit trails are core primitives — not bolt-ons."},
            {"title": "Built for African scale", "body": "Designed for the multi-currency, multi-rail, low-bandwidth realities of doing business across the continent."},
            {"title": "Operator-grade performance", "body": "Reliable wallet transfers, predictable settlement and a uniform API surface across products."},
            {"title": "Open to partners", "body": "Banks, telcos, fleets and merchants integrate at the rail — not above it."},
        ],
    },
    {
        "type": "stat_strip",
        "eyebrow": "Honest numbers",
        "items": [
            {"value": "7", "label": "Products in the ecosystem"},
            {"value": "1", "label": "Unified wallet"},
            {"value": "May 2026", "label": "First products live"},
            {"value": "Cameroon", "label": "Founding market"},
        ],
    },
    {
        "type": "big_quote",
        "quote": "Africa doesn't need another standalone app. It needs infrastructure that connects daily life — and lets the next ten thousand builders plug in.",
        "author": "Neba Clovis Ngwa",
        "role": "Founder & CEO, QUATA Digital",
    },
    {
        "type": "feature_grid",
        "eyebrow": "Built for",
        "title": "Operators across daily life.",
        "subtitle": "QUATA shows up wherever value moves — between people, businesses and the public services around them.",
        "columns": 4,
        "items": [
            {"title": "Merchants & SMBs", "body": "Accept payments, manage orders, settle reliably."},
            {"title": "Banks & telcos", "body": "Integrate at the rail — co-issue, co-acquire, route on shared infrastructure."},
            {"title": "Fintech builders", "body": "Build on the QUATAPAY APIs and ship in weeks."},
            {"title": "Public sector", "body": "Disbursements, identity and citizen services on a trusted rail."},
        ],
    },
    {
        "type": "cta",
        "eyebrow": "Get in touch",
        "title": "Ready to build on QUATA?",
        "subtitle": "Whether you're a merchant, a bank, an investor or a builder — there's a path. Tell us where you fit.",
        "primary_cta_label": "Become a partner",
        "primary_cta_href": "/partners",
        "secondary_cta_label": "Talk to us",
        "secondary_cta_href": "/contact",
    },
]


ABOUT_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "About QUATA Digital",
        "title": "Africa's connected digital ecosystem — built in Cameroon, for the continent.",
        "subtitle": "Founded May 2025 in Bamenda, Cameroon. We're building integrated digital infrastructure — payments, business operations and commerce — on a single rail.",
        "primary_cta_label": "Read our story",
        "primary_cta_href": "#story",
    },
    {
        "type": "rich_text",
        "width": "default",
        "body": (
            "## Why we exist\n\n"
            "Across Africa, millions of businesses and individuals operate in a fragmented digital "
            "environment — payments are unreliable, business tools are disconnected, and scaling "
            "across markets remains unnecessarily complex. Global solutions exist but are rarely "
            "designed for the realities of African markets, leaving a critical gap between "
            "potential and execution.\n\n"
            "QUATA Digital exists to close that gap. We're building an integrated ecosystem — "
            "payments, business infrastructure, commerce surfaces and more — designed to make "
            "it easier for anyone, anywhere in Africa, to start, run and scale a business "
            "without friction."
        ),
    },
    {
        "type": "big_quote",
        "quote": "We're not bolting another app onto the continent. We're laying rail.",
        "author": "Neba Clovis Ngwa",
        "role": "Founder & CEO",
    },
    {
        "type": "timeline",
        "title": "Our story so far.",
        "items": [
            {"date": "May 2025", "title": "QUATA Digital founded", "body": "Incorporated in Bamenda, Cameroon. Foundational architecture work begins."},
            {"date": "Q4 2025", "title": "Engineering build-out", "body": "Backend rail, payment infrastructure, identity layer and admin cockpit completed in private beta."},
            {"date": "May 2026", "title": "QUATAPAY + ABAQWA launch", "body": "First two products go live for merchants in Cameroon."},
            {"date": "2026 onward", "title": "Ecosystem expansion", "body": "QUATAFOOD, 88BASKET, 88BRICKZ, O3MALL and QMEDIQ ship in phased rollouts."},
        ],
    },
    {
        "type": "feature_grid",
        "eyebrow": "What we believe",
        "title": "Four values, no slogans.",
        "columns": 2,
        "items": [
            {"title": "Useful at scale", "body": "Anything we ship has to work for one user and a million users at the same price-per-transaction."},
            {"title": "Built in Africa for Africa", "body": "Designed for African networks, currencies, regulators and customer behaviour. Not a translation."},
            {"title": "Trust by default", "body": "Compliance, audit trails and fraud monitoring are core — not bolt-ons we add when something goes wrong."},
            {"title": "Connected, not bundled", "body": "Each product stands alone, but is more useful with the rest. No forced bundles."},
        ],
    },
    {
        "type": "cta",
        "title": "Want to be part of what we're building?",
        "subtitle": "Whether you're an operator, a partner, an investor or a candidate — we'd love to hear from you.",
        "primary_cta_label": "See open roles",
        "primary_cta_href": "/careers",
        "secondary_cta_label": "Get in touch",
        "secondary_cta_href": "/contact",
    },
]


ECOSYSTEM_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "centered",
        "eyebrow": "The ecosystem",
        "title": "Seven products. One operating system.",
        "subtitle": "Each product solves a real problem in payments, business operations or commerce — and they're stronger together because they share a wallet, an identity and an infrastructure layer.",
    },
    {
        "type": "feature_grid",
        "eyebrow": "Three layers",
        "title": "Payments, operations, commerce.",
        "subtitle": "Every product on the rail belongs to one of three layers — and each layer makes the next one cheaper, faster and more useful.",
        "columns": 3,
        "items": [
            {"title": "Payments — QUATAPAY", "body": "Multi-channel payments (Mobile Money + cards), merchant dashboard, payment links and QR. The rail under everything else."},
            {"title": "Operations — ABAQWA", "body": "Inventory, sales tracking and analytics for the businesses accepting QUATAPAY. Operations meets settlement."},
            {"title": "Commerce — QUATAFOOD, 88BASKET, 88BRICKZ, O3MALL, QMEDIQ", "body": "Consumer surfaces — food, retail, real estate, healthcare — that all share the same wallet and identity."},
        ],
    },
    {
        "type": "cta",
        "title": "Build on QUATA.",
        "subtitle": "Whether you want to integrate at the rail or partner with one of the surface products, there's a path.",
        "primary_cta_label": "Become a partner",
        "primary_cta_href": "/partners",
    },
]


PARTNERS_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "centered",
        "eyebrow": "Partner gateway",
        "title": "Four ways to plug in.",
        "subtitle": "QUATA is open by design. Pick the path that matches what you bring to the ecosystem.",
    },
    {
        "type": "feature_grid",
        "title": "The four paths.",
        "columns": 2,
        "items": [
            {"title": "Business partners", "body": "Merchants accepting QUATAPAY, vendors on the commerce surfaces, distributors moving QUATA-powered products."},
            {"title": "Strategic partners", "body": "Banks, telcos and infrastructure providers integrating at the rail."},
            {"title": "Investors", "body": "Capital partners backing the ecosystem build-out across Africa."},
            {"title": "Service partners", "body": "Riders, drivers, agents and field operators powering the daily flow."},
        ],
    },
    {
        "type": "cta",
        "title": "See your path?",
        "subtitle": "Pick a path and submit a partner application — we respond within three business days.",
        "primary_cta_label": "Business partners",
        "primary_cta_href": "/partners/business",
        "secondary_cta_label": "All four paths",
        "secondary_cta_href": "#paths",
    },
]


CAREERS_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Careers",
        "title": "Build infrastructure for a billion people.",
        "subtitle": "We're hiring across engineering, partnerships, operations and growth as we approach the May 2026 launch of QUATAPAY and ABAQWA.",
        "primary_cta_label": "See open roles",
        "primary_cta_href": "#open-roles",
    },
    {
        "type": "feature_grid",
        "eyebrow": "Why QUATA",
        "title": "What you get.",
        "columns": 3,
        "items": [
            {"title": "Real ownership", "body": "Small team, big surface. Whatever you ship, you ship end-to-end."},
            {"title": "Continental scale", "body": "Build infrastructure that serves businesses across Africa from day one."},
            {"title": "Founder-direct", "body": "Work with the founder, the product team and the operations team. No layers."},
        ],
    },
    {
        "type": "cta",
        "title": "Don't see your role?",
        "subtitle": "We're growing across the board. Tell us what you do and where you want to plug in.",
        "primary_cta_label": "Get in touch",
        "primary_cta_href": "/contact",
    },
]


CONTACT_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "centered",
        "eyebrow": "Contact",
        "title": "Talk to the QUATA team.",
        "subtitle": "Whether you're a merchant, a partner, an investor or you've got a question about an open role — drop us a line and we'll get back within two business days.",
    },
    {
        "type": "feature_grid",
        "title": "Pick the right inbox.",
        "columns": 2,
        "items": [
            {"title": "General enquiries", "body": "info@quatadigital.com — anything that doesn't fit a specific path."},
            {"title": "Partnerships", "body": "Use the partner application form on /partners — it routes to the right team automatically."},
            {"title": "Press", "body": "press@quatadigital.com — interviews, statements, fact-checks."},
            {"title": "Security", "body": "security@quatadigital.com — responsible disclosure of vulnerabilities."},
        ],
    },
    {
        "type": "newsletter_cta",
        "title": "Get the inside line on what we ship.",
        "subtitle": "Monthly updates from the QUATA team — no fluff, no pitches.",
    },
]


PRIVACY_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Privacy policy",
        "title": "How we handle your data.",
        "subtitle": "Effective on first product launch (May 2026). This policy explains what personal data QUATA Digital collects, how we process it, who we share it with, and the rights you have.",
    },
    {
        "type": "rich_text",
        "width": "default",
        "body": (
            "## 1. Who we are\n\n"
            "QUATA Digital Enterprise (\"QUATA\", \"we\", \"our\", \"us\") is the controller of the personal "
            "data collected through this website and our products. We are registered in Cameroon under "
            "RC/BDA/2025A/189 (Tax ID M052517750267W) and operate from Bamenda, North West Region, "
            "Cameroon.\n\n"
            "## 2. Why we collect data\n\n"
            "We collect and process personal data only for the purpose of:\n\n"
            "- Providing payment and business services\n"
            "- Improving platform performance\n"
            "- Ensuring security and fraud prevention\n"
            "- Meeting legal and regulatory requirements\n\n"
            "## 3. What we collect\n\n"
            "- Contact information (name, phone, email)\n"
            "- Business information (for merchants and partners)\n"
            "- Transaction data (for payment processing)\n"
            "- Technical data (device, IP, usage analytics)\n\n"
            "## 4. How we protect your data\n\n"
            "We implement industry-standard safeguards including encryption in transit, secure APIs and "
            "access controls. Sensitive data is encrypted at rest and access is restricted to authorised "
            "personnel.\n\n"
            "## 5. Data sharing\n\n"
            "We do not sell personal data. Data may be shared only with:\n\n"
            "- Payment processors and financial partners (for transaction execution)\n"
            "- Regulatory authorities (where required by law)\n"
            "- Service providers under strict confidentiality agreements\n\n"
            "## 6. Your rights\n\n"
            "Depending on where you live, you may have rights to access, correct, port, delete or restrict "
            "the processing of your personal data. To exercise any of these rights, email "
            "privacy@quatadigital.com.\n\n"
            "## 7. Data residency\n\n"
            "Primary data storage is hosted on secure cloud infrastructure. Data may be processed in "
            "multiple regions depending on service optimisation and availability. We aim to align with "
            "local data-protection regulations as we expand into new markets.\n\n"
            "## 8. Compliance posture\n\n"
            "QUATA Digital is aligning operations with key data-protection frameworks: GDPR (compliance-"
            "oriented design), NDPR (planned for Nigerian expansion) and POPIA (considered for South "
            "African market entry). We design for user consent, data minimisation, secure processing "
            "and transparent usage.\n\n"
            "## 9. Changes to this policy\n\n"
            "We may update this policy from time to time. The latest version is always available on this "
            "page, with the \"effective date\" at the top.\n\n"
            "## 10. Contact\n\n"
            "Questions or requests: privacy@quatadigital.com"
        ),
    },
]


TERMS_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Terms of service",
        "title": "The agreement between you and QUATA.",
        "subtitle": "Effective on first product launch (May 2026). By using QUATA Digital services, you agree to these terms.",
    },
    {
        "type": "rich_text",
        "width": "default",
        "body": (
            "## 1. Use of services\n\n"
            "By using QUATA Digital services, you agree to use them in compliance with applicable laws "
            "and regulations.\n\n"
            "## 2. Eligibility\n\n"
            "You must be at least 18 years old, or the legal age of majority in your jurisdiction, to "
            "use QUATA services.\n\n"
            "## 3. Account responsibilities\n\n"
            "You are responsible for maintaining the security of your account credentials and for all "
            "activities that occur under your account.\n\n"
            "## 4. Acceptable use\n\n"
            "You agree not to use QUATA services for fraudulent, illegal or harmful activities.\n\n"
            "## 5. Service availability\n\n"
            "We aim for high availability but do not guarantee uninterrupted service. Scheduled "
            "maintenance and emergency outages may occur.\n\n"
            "## 6. Fees and payments\n\n"
            "Fees, where applicable, are listed in your service agreement or product pricing page. "
            "QUATA reserves the right to revise fees with reasonable advance notice.\n\n"
            "## 7. Intellectual property\n\n"
            "QUATA retains all rights to its software, brand and content. You retain rights to your "
            "own data; you grant QUATA a limited licence to process it for the purpose of providing "
            "services.\n\n"
            "## 8. Liability\n\n"
            "To the maximum extent permitted by law, QUATA's liability is limited to fees paid for the "
            "service in the twelve months preceding the claim.\n\n"
            "## 9. Termination\n\n"
            "We may suspend or terminate accounts that violate these terms. You may close your account "
            "at any time.\n\n"
            "## 10. Governing law\n\n"
            "These terms are governed by the laws of Cameroon.\n\n"
            "## 11. Changes to these terms\n\n"
            "We may update these terms periodically. Continued use after changes constitutes acceptance "
            "of the updated terms.\n\n"
            "## 12. Contact\n\n"
            "Questions: legal@quatadigital.com"
        ),
    },
]


SECURITY_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Security",
        "title": "Security is a primitive, not a feature.",
        "subtitle": "How we protect customer data, the disclosure path for security researchers, and the compliance posture we're building toward.",
    },
    {
        "type": "feature_grid",
        "eyebrow": "Security pillars",
        "title": "What we do, by default.",
        "columns": 3,
        "items": [
            {"title": "Encryption", "body": "TLS 1.2+ in transit. Sensitive data at rest is encrypted with AES-256."},
            {"title": "Access controls", "body": "Role-based permissions, mandatory 2FA for super-admin, account lockout after repeated failures."},
            {"title": "Audit trail", "body": "Every state-changing action — actor, IP, user-agent, timestamp — is logged and retained for 90 days."},
            {"title": "Rate limiting", "body": "Public forms and login throttled at the edge to deter automated abuse."},
            {"title": "Bot protection", "body": "hCaptcha on every public form prevents scripted submissions."},
            {"title": "Input validation", "body": "Pydantic schemas reject malformed payloads at the API boundary; uploads are extension- and size-checked."},
        ],
    },
    {
        "type": "faq",
        "title": "Common questions.",
        "items": [
            {
                "question": "How do I report a security vulnerability?",
                "answer": "Email security@quatadigital.com with details. We acknowledge within one business day and aim to remediate within 30 days for high-severity issues. We don't currently run a paid bug-bounty programme, but we do credit researchers in our disclosure log.",
            },
            {
                "question": "Is QUATA SOC 2 / ISO 27001 / PCI-DSS certified?",
                "answer": "Not yet. We're building toward these frameworks as we approach launch and will publish certification milestones as they're achieved.",
            },
            {
                "question": "Where is customer data hosted?",
                "answer": "On secure cloud infrastructure with encryption at rest and in transit. Data residency policies will tighten as we expand into markets with specific requirements (NDPR for Nigeria, POPIA for South Africa).",
            },
            {
                "question": "What happens if I lose my 2FA device?",
                "answer": "Use one of the eight recovery codes you saved when you enrolled. If you've lost those too, the engineering team can help — but recovery requires identity verification.",
            },
        ],
    },
    {
        "type": "cta",
        "title": "Have a security concern?",
        "subtitle": "We take responsible disclosure seriously. Email us directly and we'll get back within one business day.",
        "primary_cta_label": "security@quatadigital.com",
        "primary_cta_href": "mailto:security@quatadigital.com",
    },
]


# ---------------------------------------------------------------------------
# Per-product pages (page_type=product, strict allow-list)
# ---------------------------------------------------------------------------

# A product page can use: hero, feature_grid, icon_badge, stat_strip,
# image_text, process_steps, testimonials, faq, cta, rich_text.

QUATAPAY_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Payments",
        "title": "QUATAPAY — all-in-one payments for modern African businesses.",
        "subtitle": "Mobile Money + cards + payment links + QR. One merchant account, one dashboard, one settlement window — built for the realities of doing business in Africa.",
        "primary_cta_label": "Become a merchant",
        "primary_cta_href": "/partners/business",
        "secondary_cta_label": "Talk to sales",
        "secondary_cta_href": "/contact",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Beta", "label": "Status", "caption": "Pilot merchants onboarding now"},
            {"value": "May 2026", "label": "Public launch"},
            {"value": "Cameroon", "label": "Founding market"},
            {"value": "MoMo + Cards", "label": "Payment rails"},
        ],
    },
    {
        "type": "feature_grid",
        "eyebrow": "What's in the box",
        "title": "Everything a merchant needs to accept payments.",
        "columns": 3,
        "items": [
            {"title": "Multi-channel payments", "body": "Mobile Money (MTN MoMo, Orange Money) and card networks (Visa, Mastercard) — accept every meaningful payment method from one merchant account."},
            {"title": "Merchant dashboard", "body": "Real-time transaction tracking, settlement visibility and downloadable reports for finance teams."},
            {"title": "Payment links & QR", "body": "Sell anywhere — share a link or print a QR. No website required."},
            {"title": "One settlement window", "body": "All your channels, one settlement schedule. Predictable cashflow."},
            {"title": "Built-in fraud monitoring", "body": "Automated screening on every transaction; flagged events surface in the dashboard."},
            {"title": "Real support", "body": "Direct email + WhatsApp lines to a human, not a chatbot."},
        ],
    },
    {
        "type": "process_steps",
        "eyebrow": "Onboarding",
        "title": "Live in days, not months.",
        "items": [
            {"title": "Apply", "body": "Submit a business partner application with KYB documents."},
            {"title": "Verify", "body": "We review your business and confirm any compliance steps required for your category."},
            {"title": "Integrate", "body": "Use the dashboard, payment links and QR — or plug in the API for in-app payments."},
            {"title": "Settle", "body": "Receive your first payouts on the agreed schedule. Support is one message away."},
        ],
    },
    {
        "type": "faq",
        "title": "Common questions.",
        "items": [
            {"question": "Which payment methods does QUATAPAY support at launch?", "answer": "Mobile Money (MTN MoMo and Orange Money) and card networks (Visa, Mastercard). More rails are added as we expand into new markets."},
            {"question": "How fast is settlement?", "answer": "T+1 by default (next business day). Custom schedules available for higher-volume merchants."},
            {"question": "Do I need a website?", "answer": "No. Payment links and QR codes work without a site. If you do have a site, we have an API and SDKs."},
            {"question": "What does QUATAPAY cost?", "answer": "Pricing varies by volume and rail. Contact sales for a custom quote — we don't post merchant pricing publicly."},
        ],
    },
    {
        "type": "cta",
        "title": "Ready to accept payments?",
        "subtitle": "Apply as a business partner and the merchant onboarding team will be in touch within three business days.",
        "primary_cta_label": "Become a merchant",
        "primary_cta_href": "/partners/business",
    },
]

ABAQWA_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Business operations",
        "title": "ABAQWA — powering smarter business operations across Africa.",
        "subtitle": "Inventory, sales, analytics — one platform that integrates seamlessly with QUATAPAY so every transaction settles into the right ledger automatically.",
        "primary_cta_label": "Become a partner",
        "primary_cta_href": "/partners",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Beta", "label": "Status"},
            {"value": "May 2026", "label": "Public launch"},
            {"value": "Native", "label": "QUATAPAY integration"},
        ],
    },
    {
        "type": "feature_grid",
        "title": "Built for operators who outgrew spreadsheets.",
        "columns": 3,
        "items": [
            {"title": "Inventory & sales", "body": "Track stock, sales and orders in one place — no spreadsheets required."},
            {"title": "Analytics that explain", "body": "Live dashboards showing what's selling, what's slow and what to restock."},
            {"title": "Built for QUATAPAY", "body": "Every transaction recorded in ABAQWA settles through QUATAPAY automatically."},
        ],
    },
    {
        "type": "icon_badge",
        "title": "Operations + payments on one rail.",
        "body": "ABAQWA isn't a separate app you have to reconcile against — it's the same rail QUATAPAY runs on, just with the operations layer surfaced. Numbers add up by default.",
    },
    {
        "type": "cta",
        "title": "See ABAQWA in action.",
        "subtitle": "We're onboarding pilot merchants ahead of the May 2026 launch.",
        "primary_cta_label": "Apply for early access",
        "primary_cta_href": "/partners/business",
    },
]

QUATAFOOD_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Food",
        "title": "QUATAFOOD — food delivery and commerce, made simple.",
        "subtitle": "Food ordering and delivery for African cities — connecting customers with restaurants and food vendors in one seamless digital experience.",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Coming soon", "label": "Status"},
            {"value": "Phased", "label": "City-by-city rollout"},
        ],
    },
    {
        "type": "feature_grid",
        "title": "Three things QUATAFOOD does well.",
        "columns": 3,
        "items": [
            {"title": "Order, pay, deliver", "body": "Customers browse menus, pay with QUATAPAY and track delivery in real time."},
            {"title": "Vendor onboarding", "body": "Restaurants and kitchens go live in days, not months."},
            {"title": "Delivery coordination", "body": "Built-in dispatch keeps couriers and orders in sync."},
        ],
    },
    {
        "type": "cta",
        "title": "Are you a restaurant or kitchen?",
        "subtitle": "Apply as a service partner now — we'll be in touch when we open in your city.",
        "primary_cta_label": "Become a partner",
        "primary_cta_href": "/partners/service",
    },
]

EIGHTYEIGHT_BASKET_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Commerce",
        "title": "88BASKET — your everyday shopping, reimagined.",
        "subtitle": "An e-commerce platform connecting customers with sellers through a modern digital marketplace built for African shoppers.",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Planned", "label": "Status"},
            {"value": "Continental", "label": "Vision"},
        ],
    },
    {
        "type": "feature_grid",
        "title": "What 88BASKET will do.",
        "columns": 3,
        "items": [
            {"title": "Online marketplace", "body": "A unified place for everyday goods — household, electronics, fashion and more."},
            {"title": "Vendor onboarding", "body": "Sellers go live with a digital storefront in minutes."},
            {"title": "Integrated checkout", "body": "QUATAPAY-native checkout means one wallet, fewer drop-offs at payment."},
        ],
    },
    {
        "type": "cta",
        "title": "Want to be among the first sellers?",
        "primary_cta_label": "Apply as a partner",
        "primary_cta_href": "/partners/business",
    },
]

EIGHTYEIGHT_BRICKZ_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Real Estate",
        "title": "88BRICKZ — digital infrastructure for modern real estate.",
        "subtitle": "Simplifying property discovery, transactions and management — bringing transparency and efficiency to the African real estate sector.",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Coming soon", "label": "Status"},
        ],
    },
    {
        "type": "feature_grid",
        "title": "What 88BRICKZ will offer.",
        "columns": 3,
        "items": [
            {"title": "Verified property listings", "body": "Trusted listings with verification on the title side, not just the photo."},
            {"title": "Digital transaction support", "body": "Earnest deposits, deeds and milestones tracked end-to-end."},
            {"title": "Property management tools", "body": "Tenant payments, maintenance requests and analytics in one place."},
        ],
    },
    {
        "type": "cta",
        "title": "Are you an agent or developer?",
        "primary_cta_label": "Apply as a strategic partner",
        "primary_cta_href": "/partners/strategic",
    },
]

O3MALL_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Commerce",
        "title": "O3MALL — the future of digital marketplaces.",
        "subtitle": "A large-scale digital commerce platform bringing together multiple vendors and services into a unified online marketplace experience.",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Planned", "label": "Status"},
        ],
    },
    {
        "type": "feature_grid",
        "title": "What O3MALL is being built to do.",
        "columns": 3,
        "items": [
            {"title": "Multi-vendor marketplace", "body": "Bring small and large vendors into a single, searchable surface."},
            {"title": "Digital storefronts", "body": "Every vendor gets a branded mini-site, not a barebones list."},
            {"title": "Centralised management", "body": "Order, fulfilment and payment management surfaced for both vendors and customers."},
        ],
    },
    {
        "type": "cta",
        "title": "Want updates as we approach launch?",
        "primary_cta_label": "Stay in touch",
        "primary_cta_href": "/contact",
    },
]

QMEDIQ_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Health",
        "title": "QMEDIQ — digital healthcare access, simplified.",
        "subtitle": "Improving access to medical services, consultations and healthcare management through technology, built for African healthcare realities.",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "Planned", "label": "Status"},
        ],
    },
    {
        "type": "feature_grid",
        "title": "What QMEDIQ aims to enable.",
        "columns": 3,
        "items": [
            {"title": "Digital health access", "body": "Surface trusted providers, schedule appointments, and access records — without the paper queue."},
            {"title": "Appointment management", "body": "Book, reschedule and remind, in one place. Less wasted clinic time."},
            {"title": "Healthcare service integration", "body": "Pharmacies, labs and clinics connected on the same rail."},
        ],
    },
    {
        "type": "cta",
        "title": "Are you a provider, lab or pharmacy?",
        "primary_cta_label": "Apply as a strategic partner",
        "primary_cta_href": "/partners/strategic",
    },
]


# ---------------------------------------------------------------------------
# Per-partner-type pages (page_type=partner_type, strict allow-list)
# ---------------------------------------------------------------------------

# A partner_type page can use: hero, feature_grid, icon_badge,
# process_steps, stat_strip, faq, cta, rich_text.

PARTNERS_BUSINESS_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Business partners",
        "title": "Accept QUATAPAY. Run on ABAQWA. Show up across the ecosystem.",
        "subtitle": "For merchants, vendors and distributors who want one rail for payments, operations and discovery — built for the realities of African commerce.",
        "primary_cta_label": "Apply now",
        "primary_cta_href": "#apply",
    },
    {
        "type": "feature_grid",
        "eyebrow": "Why business partners pick QUATA",
        "title": "What you get on day one.",
        "columns": 2,
        "items": [
            {"title": "Multi-rail payments", "body": "Mobile Money + cards + payment links + QR. One merchant account, one settlement window."},
            {"title": "Operations on the same rail", "body": "ABAQWA tracks inventory and sales; numbers reconcile against QUATAPAY automatically."},
            {"title": "Discovery across the ecosystem", "body": "Where it makes sense, surface in QUATAFOOD, 88BASKET and other consumer products on the rail."},
            {"title": "Real support", "body": "Direct lines to humans, not chatbots. Onboarding done in days, not weeks."},
        ],
    },
    {
        "type": "process_steps",
        "eyebrow": "How onboarding works",
        "title": "From application to live, in four steps.",
        "items": [
            {"title": "Submit", "body": "Fill the partner application below — basics about your business and what you sell."},
            {"title": "Review", "body": "We respond within three business days with KYB documents to gather."},
            {"title": "Integrate", "body": "Use the merchant dashboard, payment links and QR — or plug into the API."},
            {"title": "Go live", "body": "Settle reliably from day one. Support is one message away."},
        ],
    },
    {
        "type": "faq",
        "title": "Common questions from merchants.",
        "items": [
            {"question": "Do you have a minimum monthly volume?", "answer": "No formal minimum at launch. We're prioritising onboarding any business with a clear product/service and verified compliance basics."},
            {"question": "What does it cost?", "answer": "Pricing depends on volume and rail. Contact sales for a custom quote — we don't publish merchant pricing publicly."},
            {"question": "How long does onboarding take?", "answer": "Typically 3–7 business days from application to live, depending on KYB turnaround."},
            {"question": "Can I keep my existing payment provider?", "answer": "Yes — QUATAPAY can run alongside an existing rail. Some merchants migrate fully over time once they see the dashboard."},
        ],
    },
    {
        "type": "cta",
        "eyebrow": "Apply",
        "title": "Ready to plug in?",
        "subtitle": "We respond within three business days. Use the form on the page below.",
        "primary_cta_label": "Apply as a business partner",
        "primary_cta_href": "/partners/business#apply",
    },
]

PARTNERS_STRATEGIC_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Strategic partners",
        "title": "Integrate at the rail. Build with us, not above us.",
        "subtitle": "For banks, telcos, fleets and infrastructure providers who want to co-issue, co-acquire or route on the same rail QUATA's products run on.",
        "primary_cta_label": "Apply",
        "primary_cta_href": "#apply",
    },
    {
        "type": "feature_grid",
        "eyebrow": "What we offer strategic partners",
        "title": "Connected by design.",
        "columns": 2,
        "items": [
            {"title": "Rail-level integration", "body": "Co-issue and co-acquire on shared infrastructure. No need to wrap each consumer product separately."},
            {"title": "Joint go-to-market", "body": "We bring product surfaces; you bring distribution. We split the work transparently."},
            {"title": "Compliance-first", "body": "All flows designed for regulator review. Audit trails, BIN management and reporting are first-class."},
            {"title": "Long horizon", "body": "We optimise for partnerships that compound — not transactional vendor relationships."},
        ],
    },
    {
        "type": "process_steps",
        "title": "How strategic partnerships kick off.",
        "items": [
            {"title": "Intro call", "body": "30 minutes to understand fit and what each side brings."},
            {"title": "Term sheet", "body": "We draft commercial + technical terms in a shareable doc."},
            {"title": "Pilot scope", "body": "Small, measurable. Three months max, with named success criteria."},
            {"title": "Scale", "body": "If the pilot works, we scale together. If not, we say so honestly and move on."},
        ],
    },
    {
        "type": "cta",
        "title": "Let's compare notes.",
        "subtitle": "Drop a line, schedule the intro call, see if there's a fit.",
        "primary_cta_label": "Apply as a strategic partner",
        "primary_cta_href": "/partners/strategic#apply",
    },
]

PARTNERS_INVESTOR_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Investors",
        "title": "Capital that compounds — across products, across markets.",
        "subtitle": "QUATA is building integrated digital infrastructure for Africa. We're selectively talking to investors who back long-horizon platform plays.",
        "primary_cta_label": "Apply",
        "primary_cta_href": "#apply",
    },
    {
        "type": "stat_strip",
        "items": [
            {"value": "May 2025", "label": "Founded"},
            {"value": "Cameroon", "label": "Founding market"},
            {"value": "May 2026", "label": "First products live"},
            {"value": "7", "label": "Products on the rail"},
        ],
    },
    {
        "type": "feature_grid",
        "eyebrow": "Why now",
        "title": "Three reasons we're investable.",
        "columns": 3,
        "items": [
            {"title": "Single rail, many surfaces", "body": "Each product on the rail strengthens the rest. Compounding economics, not standalone bets."},
            {"title": "Founder + ops in-market", "body": "Built in Bamenda. We understand the regulatory, network and customer realities first-hand."},
            {"title": "Trust by default", "body": "Compliance, audit and fraud monitoring are core primitives — not bolted on after a near-miss."},
        ],
    },
    {
        "type": "cta",
        "title": "Want to talk?",
        "subtitle": "Apply with a brief intro. We respond to qualified investors within five business days.",
        "primary_cta_label": "Apply as an investor",
        "primary_cta_href": "/partners/investor#apply",
    },
]

PARTNERS_SERVICE_SECTIONS: list[dict] = [
    {
        "type": "hero",
        "variant": "default",
        "eyebrow": "Service partners",
        "title": "Power the daily flow on the QUATA rail.",
        "subtitle": "For riders, drivers, agents and field operators — the people who turn digital orders into delivered goods and services.",
        "primary_cta_label": "Apply",
        "primary_cta_href": "#apply",
    },
    {
        "type": "feature_grid",
        "eyebrow": "What service partners get",
        "title": "Reliable work, paid through one wallet.",
        "columns": 2,
        "items": [
            {"title": "Steady demand", "body": "Volume across QUATAFOOD, 88BASKET and field operations — not a single-app gamble."},
            {"title": "Paid through QUATAPAY", "body": "One wallet, predictable settlement. Cash out as you choose."},
            {"title": "Supportive ops team", "body": "Real humans handling onboarding and dispute resolution. Not a chatbot."},
            {"title": "Tools that respect your time", "body": "Mobile-first, low-bandwidth-friendly. Designed for the network you actually have."},
        ],
    },
    {
        "type": "process_steps",
        "title": "Three steps to get on the rail.",
        "items": [
            {"title": "Apply", "body": "Tell us where you operate and the kind of work you do."},
            {"title": "Verify", "body": "Identity + work documents — quick, but real."},
            {"title": "Activate", "body": "We onboard you to the apps and you start receiving work."},
        ],
    },
    {
        "type": "cta",
        "title": "Ready to start?",
        "primary_cta_label": "Apply as a service partner",
        "primary_cta_href": "/partners/service#apply",
    },
]


# ---------------------------------------------------------------------------
# Catalogue
# ---------------------------------------------------------------------------

DEFAULTS: dict[str, list[dict]] = {
    # General pages
    "home": HOME_SECTIONS,
    "about": ABOUT_SECTIONS,
    "ecosystem": ECOSYSTEM_SECTIONS,
    "partners": PARTNERS_SECTIONS,
    "careers": CAREERS_SECTIONS,
    "contact": CONTACT_SECTIONS,
    "privacy": PRIVACY_SECTIONS,
    "terms": TERMS_SECTIONS,
    "security": SECURITY_SECTIONS,
    # Per-product pages (page_type=product)
    "ecosystem/quatapay": QUATAPAY_SECTIONS,
    "ecosystem/abaqwa": ABAQWA_SECTIONS,
    "ecosystem/quatafood": QUATAFOOD_SECTIONS,
    "ecosystem/88basket": EIGHTYEIGHT_BASKET_SECTIONS,
    "ecosystem/88brickz": EIGHTYEIGHT_BRICKZ_SECTIONS,
    "ecosystem/o3mall": O3MALL_SECTIONS,
    "ecosystem/qmediq": QMEDIQ_SECTIONS,
    # Per-partner-type pages (page_type=partner_type)
    "partners/business": PARTNERS_BUSINESS_SECTIONS,
    "partners/strategic": PARTNERS_STRATEGIC_SECTIONS,
    "partners/investor": PARTNERS_INVESTOR_SECTIONS,
    "partners/service": PARTNERS_SERVICE_SECTIONS,
}


def seed_default_section_content(db: Session) -> int:
    """For each page in DEFAULTS, if the row exists and has zero sections,
    fill it with the default starter sections. Returns the number of
    pages filled.

    Critically: only fills empty rows. If the boss has already added
    sections (even one), this is a no-op for that row — boss edits win.
    Pages stay UNPUBLISHED so the boss reviews before going live.
    """
    filled = 0
    for slug, sections in DEFAULTS.items():
        page = db.query(PageContent).filter(PageContent.slug == slug).first()
        if page is None:
            # Page doesn't exist yet — let `seed_default_pages` create it
            # first; it'll be filled on the next boot.
            continue
        if page.sections and len(page.sections) > 0:
            continue
        try:
            page.sections = validate_sections(sections)
            filled += 1
        except Exception:  # noqa: BLE001
            # Defensive — bad seed payload should never silently pass.
            # In dev this raises during validate_sections; logging here
            # lets prod boot continue with the page empty if a section
            # type was renamed and a payload wasn't updated.
            continue
    if filled:
        db.commit()
    return filled
